default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: feed_list_dev

test:
  <<: *default
  database: feed_list_test

production:
  <<: *default
  database: feed_list_pd
  username: feed_list
  password: <%= ENV['FEED_LIST_DB_PWD'] %>
